[2024-08-05T16:14:36.521+0000] {scheduler_job_runner.py:781} ERROR - Executor reports task instance <TaskInstance: Credit_score_pipeline.load_data scheduled__2024-08-03T10:00:00+00:00 [queued]> finished (success) although the task says it's queued. (Info: None) Was the task killed externally?
