[2024-08-23T09:37:01.692+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Credit_score_pipeline_v03.train_model scheduled__2024-08-22T00:00:00+00:00 [queued]>
[2024-08-23T09:37:01.713+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Credit_score_pipeline_v03.train_model scheduled__2024-08-22T00:00:00+00:00 [queued]>
[2024-08-23T09:37:01.724+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 6
[2024-08-23T09:37:01.739+0000] {taskinstance.py:2214} INFO - Executing <Task(PythonOperator): train_model> on 2024-08-22 00:00:00+00:00
[2024-08-23T09:37:01.753+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'Credit_score_pipeline_v03', 'train_model', 'scheduled__2024-08-22T00:00:00+00:00', '--job-id', '288', '--raw', '--subdir', 'DAGS_FOLDER/credit_score.py', '--cfg-path', '/tmp/tmp797eiii7']
[2024-08-23T09:37:01.758+0000] {standard_task_runner.py:88} INFO - Job 288: Subtask train_model
[2024-08-23T09:37:01.749+0000] {standard_task_runner.py:60} INFO - Started process 114 to run task
[2024-08-23T09:37:02.592+0000] {task_command.py:423} INFO - Running <TaskInstance: Credit_score_pipeline_v03.train_model scheduled__2024-08-22T00:00:00+00:00 [running]> on host f022a2ec5bf1
[2024-08-23T09:37:02.924+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Credit_score_pipeline_v03' AIRFLOW_CTX_TASK_ID='train_model' AIRFLOW_CTX_EXECUTION_DATE='2024-08-22T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-08-22T00:00:00+00:00'
[2024-08-23T09:37:02.936+0000] {taskinstance.py:2728} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/credit_score.py", line 127, in train_model
    train_data = pd.read_csv('/opt/airflow/dags/train_data.csv')
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 912, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 577, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 1407, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 1661, in _make_engine
    self.handles = get_handle(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/common.py", line 859, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/dags/train_data.csv'
[2024-08-23T09:37:02.957+0000] {taskinstance.py:1149} INFO - Marking task as UP_FOR_RETRY. dag_id=Credit_score_pipeline_v03, task_id=train_model, execution_date=20240822T000000, start_date=20240823T093701, end_date=20240823T093702
[2024-08-23T09:37:02.978+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 288 for task train_model ([Errno 2] No such file or directory: '/opt/airflow/dags/train_data.csv'; 114)
[2024-08-23T09:37:03.022+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-08-23T09:37:03.077+0000] {taskinstance.py:3309} INFO - 0 downstream tasks scheduled from follow-on schedule check
