[2024-08-05T16:40:38.698+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Credit_score_pipeline_v01.load_data scheduled__2024-08-04T00:00:00+00:00 [queued]>
[2024-08-05T16:40:38.709+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Credit_score_pipeline_v01.load_data scheduled__2024-08-04T00:00:00+00:00 [queued]>
[2024-08-05T16:40:38.710+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 6
[2024-08-05T16:40:38.804+0000] {taskinstance.py:2214} INFO - Executing <Task(MySqlOperator): load_data> on 2024-08-04 00:00:00+00:00
[2024-08-05T16:40:38.817+0000] {standard_task_runner.py:60} INFO - Started process 854 to run task
[2024-08-05T16:40:38.820+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'Credit_score_pipeline_v01', 'load_data', 'scheduled__2024-08-04T00:00:00+00:00', '--job-id', '152', '--raw', '--subdir', 'DAGS_FOLDER/credit_score.py', '--cfg-path', '/tmp/tmp2oq4mp15']
[2024-08-05T16:40:38.823+0000] {standard_task_runner.py:88} INFO - Job 152: Subtask load_data
[2024-08-05T16:40:38.902+0000] {task_command.py:423} INFO - Running <TaskInstance: Credit_score_pipeline_v01.load_data scheduled__2024-08-04T00:00:00+00:00 [running]> on host dd9539b5cbac
[2024-08-05T16:40:39.062+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Credit_score_pipeline_v01' AIRFLOW_CTX_TASK_ID='load_data' AIRFLOW_CTX_EXECUTION_DATE='2024-08-04T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-08-04T00:00:00+00:00'
[2024-08-05T16:40:39.275+0000] {sql.py:276} INFO - Executing: 
        LOAD DATA LOCAL INFILE '/opt/***/dags/clean_train.csv'
        INTO TABLE credit
        FIELDS TERMINATED BY ','
        LINES TERMINATED BY '
'
        IGNORE 1 ROWS;
        
[2024-08-05T16:40:39.289+0000] {base.py:83} INFO - Using connection ID 'mysql_conn' for task execution.
[2024-08-05T16:40:39.461+0000] {base.py:83} INFO - Using connection ID 'mysql_conn' for task execution.
[2024-08-05T16:40:39.967+0000] {taskinstance.py:2728} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/operators/sql.py", line 282, in execute
    output = hook.run(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/hooks/sql.py", line 397, in run
    with closing(self.get_conn()) as conn:
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/mysql/hooks/mysql.py", line 195, in get_conn
    return MySQLdb.connect(**conn_config)
  File "/home/airflow/.local/lib/python3.8/site-packages/MySQLdb/__init__.py", line 121, in Connect
    return Connection(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/MySQLdb/connections.py", line 195, in __init__
    super().__init__(*args, **kwargs2)
MySQLdb.OperationalError: (2002, "Can't connect to server on '127.0.0.1' (115)")
[2024-08-05T16:40:39.977+0000] {taskinstance.py:1149} INFO - Marking task as UP_FOR_RETRY. dag_id=Credit_score_pipeline_v01, task_id=load_data, execution_date=20240804T000000, start_date=20240805T164038, end_date=20240805T164039
[2024-08-05T16:40:40.015+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 152 for task load_data ((2002, "Can't connect to server on '127.0.0.1' (115)"); 854)
[2024-08-05T16:40:40.033+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-08-05T16:40:40.059+0000] {taskinstance.py:3309} INFO - 0 downstream tasks scheduled from follow-on schedule check
