[2024-08-06T14:08:41.646+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Credit_score_pipeline_v04.load_data manual__2024-08-06T14:05:59.245755+00:00 [queued]>
[2024-08-06T14:08:41.657+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Credit_score_pipeline_v04.load_data manual__2024-08-06T14:05:59.245755+00:00 [queued]>
[2024-08-06T14:08:41.658+0000] {taskinstance.py:2193} INFO - Starting attempt 2 of 7
[2024-08-06T14:08:41.677+0000] {taskinstance.py:2214} INFO - Executing <Task(PostgresOperator): load_data> on 2024-08-06 14:05:59.245755+00:00
[2024-08-06T14:08:41.688+0000] {standard_task_runner.py:60} INFO - Started process 355 to run task
[2024-08-06T14:08:41.692+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'Credit_score_pipeline_v04', 'load_data', 'manual__2024-08-06T14:05:59.245755+00:00', '--job-id', '189', '--raw', '--subdir', 'DAGS_FOLDER/credit_score.py', '--cfg-path', '/tmp/tmp2m1clyos']
[2024-08-06T14:08:41.695+0000] {standard_task_runner.py:88} INFO - Job 189: Subtask load_data
[2024-08-06T14:08:41.751+0000] {task_command.py:423} INFO - Running <TaskInstance: Credit_score_pipeline_v04.load_data manual__2024-08-06T14:05:59.245755+00:00 [running]> on host 43471a75e062
[2024-08-06T14:08:41.852+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Credit_score_pipeline_v04' AIRFLOW_CTX_TASK_ID='load_data' AIRFLOW_CTX_EXECUTION_DATE='2024-08-06T14:05:59.245755+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-08-06T14:05:59.245755+00:00'
[2024-08-06T14:08:41.854+0000] {sql.py:276} INFO - Executing: 
        LOAD DATA LOCAL INFILE '/opt/***/dags/clean_train.csv'
        INTO TABLE credit
        FIELDS TERMINATED BY ','
        LINES TERMINATED BY '
'
        IGNORE 1 ROWS;
        
[2024-08-06T14:08:41.869+0000] {base.py:83} INFO - Using connection ID 'postgresql' for task execution.
[2024-08-06T14:08:41.880+0000] {base.py:83} INFO - Using connection ID 'postgresql' for task execution.
[2024-08-06T14:08:42.119+0000] {taskinstance.py:2728} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/operators/sql.py", line 282, in execute
    output = hook.run(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/hooks/sql.py", line 397, in run
    with closing(self.get_conn()) as conn:
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/postgres/hooks/postgres.py", line 161, in get_conn
    self.conn = psycopg2.connect(**conn_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "host.docker.internal" (192.168.65.254), port 5433 failed: FATAL:  password authentication failed for user "postgres"

[2024-08-06T14:08:42.129+0000] {taskinstance.py:1149} INFO - Marking task as UP_FOR_RETRY. dag_id=Credit_score_pipeline_v04, task_id=load_data, execution_date=20240806T140559, start_date=20240806T140841, end_date=20240806T140842
[2024-08-06T14:08:42.142+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 189 for task load_data (connection to server at "host.docker.internal" (192.168.65.254), port 5433 failed: FATAL:  password authentication failed for user "postgres"
; 355)
[2024-08-06T14:08:42.187+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-08-06T14:08:42.206+0000] {taskinstance.py:3309} INFO - 0 downstream tasks scheduled from follow-on schedule check
