[2024-08-05T16:16:05.397+0000] {scheduler_job_runner.py:781} ERROR - Executor reports task instance <TaskInstance: Credit_score_pipeline.load_data scheduled__2024-08-04T10:00:00+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
