[2024-08-02T08:18:30.732+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_python_dependencies_v01.get_sklearn manual__2024-08-02T08:18:29.058946+00:00 [queued]>
[2024-08-02T08:18:30.742+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_python_dependencies_v01.get_sklearn manual__2024-08-02T08:18:29.058946+00:00 [queued]>
[2024-08-02T08:18:30.743+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-08-02T08:18:30.761+0000] {taskinstance.py:2214} INFO - Executing <Task(PythonOperator): get_sklearn> on 2024-08-02 08:18:29.058946+00:00
[2024-08-02T08:18:30.781+0000] {standard_task_runner.py:60} INFO - Started process 72 to run task
[2024-08-02T08:18:30.798+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'dag_with_python_dependencies_v01', 'get_sklearn', 'manual__2024-08-02T08:18:29.058946+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_python_dependencies.py', '--cfg-path', '/tmp/tmpwa349uts']
[2024-08-02T08:18:30.803+0000] {standard_task_runner.py:88} INFO - Job 5: Subtask get_sklearn
[2024-08-02T08:18:30.925+0000] {task_command.py:423} INFO - Running <TaskInstance: dag_with_python_dependencies_v01.get_sklearn manual__2024-08-02T08:18:29.058946+00:00 [running]> on host 611c1f63d70d
[2024-08-02T08:18:31.099+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_with_python_dependencies_v01' AIRFLOW_CTX_TASK_ID='get_sklearn' AIRFLOW_CTX_EXECUTION_DATE='2024-08-02T08:18:29.058946+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-08-02T08:18:29.058946+00:00'
[2024-08-02T08:18:31.104+0000] {taskinstance.py:2728} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dag_with_python_dependencies.py", line 12, in get_sklearn
    import sklearn
ModuleNotFoundError: No module named 'sklearn'
[2024-08-02T08:18:31.205+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=dag_with_python_dependencies_v01, task_id=get_sklearn, execution_date=20240802T081829, start_date=20240802T081830, end_date=20240802T081831
[2024-08-02T08:18:31.227+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 5 for task get_sklearn (No module named 'sklearn'; 72)
[2024-08-02T08:18:31.252+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-08-02T08:18:31.289+0000] {taskinstance.py:3309} INFO - 0 downstream tasks scheduled from follow-on schedule check
